// EXCLUDE_VARIANT: normal
// EXCLUDE_VARIANT: optdescent
S = "a" @needTag(TA) Y | "b" @rejectTag(TA) Y;
Y = "y" @inheritTag(TA) @inheritTag(TB) X "y";
X = <XA | <XB;
XA = "x" @tag(TA);
XB = "x" @tag(TB);
