S = StmtList;
StmtList @array
	= @empty
	| StmtList Stmt
	;
Stmt
	= "s" ";"
	| <IfStmt
	| "{" StmtList "}"
	;
IfStmt
	= "if" "(" ")" Stmt !"else"
	| "if" "(" ")" Stmt "else" Stmt
	;

token Space @ignoreToken = [ \n\r\t]+;
