// EXCLUDE_VARIANT: normal
// EXCLUDE_VARIANT: optdescent
/*
GENERATOR_OUTPUT(normal, optdescent):
---
Warning: Parse conflict in state 13
---
*/
S = StmtList;
StmtList @array
	= @empty
	| StmtList Stmt
	;
Stmt
	= "s" ";"
	| <IfStmt
	| "{" StmtList "}"
	;
IfStmt
	= "if" "(" ")" @rejectTag(IfWithElse) Stmt @tag(IfWithoutElse)
	| "if" "(" ")" @rejectTag(IfWithoutElse) Stmt "else" Stmt @tag(IfWithElse)
	;

// Compare to https://www.digitalmars.com/articles/b69.html

token Space @ignoreToken = [ \n\r\t]+;
