// EXCLUDE_VARIANT: glr
/*
GENERATOR_OUTPUT(normal):
---
Warning: Parse conflict in state 8
---
*/
/*
GENERATOR_OUTPUT(optdescent):
---
Warning: Parse conflict in state 6
---
*/
S = A | !X B;
A = "a" | Y;
B = "b" | Y;
Y = X | "y";
X = "x";
