/*
GENERATOR_OUTPUT(normal):
---
Warning: Parse conflict in state 13
---
*/
/*
GENERATOR_OUTPUT(optdescent):
---
Warning: Parse conflict in state 17
---
*/
S = StmtList;
StmtList @array
	= @empty
	| StmtList Stmt
	;
Stmt
	= "s" ";"
	| <IfStmt
	| "{" StmtList "}"
	;
IfStmt
	= "if" "(" ")" Stmt
	| "if" "(" ")" Stmt "else" Stmt
	;

token Space @ignoreToken = [ \n\r\t]+;
