/*
GENERATOR_OUTPUT(lexer):
---
Warning: Lexer conflict for \"keyword\" Identifier
Warning: Lexer conflict for Decimal Octal
---
*/
S = Identifier | "keyword" | Decimal | Octal;
token Identifier = [a-zA-Z_] [a-zA-Z0-9]*;
token Decimal = [0-9]+;
token Octal = "0" [0-7]*;
