name: DParserGen tests

on:
  push:
    branches: [ "master", "test" ]
  pull_request:
    branches: [ "master", "test" ]

permissions:
  contents: read

jobs:
  main:
    strategy:
      fail-fast: false

      matrix:
        platform: [ linux64, win64, win32 ]
        dc: [ dmd-latest, dmd-2.100.0, ldc-latest, dmd-master ]

        exclude:
          - { platform: win32, dc: ldc-latest }
          - { platform: win64, dc: dmd-2.100.0 }

        include:
          - platform: linux64
            os: ubuntu-22.04
            model: 64

          - platform: win64
            os: windows-2022
            model: 64

          - platform: win32
            os: windows-2022
            model: 32mscoff
            extra_args: --skip-slow-examples

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: Checkout DMD
      if: ${{ matrix.extra_args != 'win32' }}
      uses: actions/checkout@v3
      with:
        path: dmd
        repository: dlang/dmd
        ref: 7bff453b5e3b16c5eab2874984ed7d973a4f9e5b
        persist-credentials: false

    - name: Checkout JSONTestSuite
      if: ${{ matrix.platform != 'win32' }}
      uses: actions/checkout@v3
      with:
        path: JSONTestSuite
        repository: nst/JSONTestSuite
        ref: d64aefb55228d9584d3e5b2433f720ea8fd00c82
        persist-credentials: false

    - name: Checkout CPython
      if: ${{ matrix.platform != 'win32' }}
      uses: actions/checkout@v3
      with:
        path: cpython
        repository: python/cpython
        ref: 3979150a0d406707f6d253d7c15fb32c1e005a77
        persist-credentials: false

    - name: 'Build & Test'
      run: |
        ${{ env.DC }} -run runtests.d --compiler ${{ env.DC }} -m${{ matrix.model }} --json-test-dir JSONTestSuite/test_parsing --dmd-dir dmd --python-test-dir cpython/Lib/test --avoid-parallel-memory-usage --github ${{ matrix.extra_args }}
